fix: ci
Signed-off-by: shaonianche <github@duanfei.org>

diff --git a/.github/workflows/get_fit.yml b/.github/workflows/get_fit.yml
--- a/.github/workflows/get_fit.yml
+++ b/.github/workflows/get_fit.yml
@@ -30,14 +30,17 @@ jobs:
         
     - name: Rename file
       run: |
-        ls "${{ env.LOCAL_PATH }}"
         cd "${{ env.LOCAL_PATH }}"
         for file in *-*-*.fit; do
             if [[ $file =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}-[0-9]{6} ]]; then
-                mv "$file" "${file:0:17}.fit"
+                if mv -n "$file" "${file:0:17}.fit"; then
+                    echo "Successfully renamed: $file -> ${file:0:17}.fit"
+                else
+                    echo "Failed to rename: $file"
+                    exit 1
+                fi
             fi
         done
-        cd ..
 
     - name: Push fit file
       run: |
